### ISSUE TITLE
ApiClient methods missing async variants

### ISSUE THREAD

**Issue by bbarry** [docusign/docusign-esign-csharp-client#294]
notably: RequestJWTUserToken, GenerateAccessToken, GetUserInfo, and RequestJWTApplicationToken

All 4 (and overloads) are making http requests but are only offered as sync methods.

**Comment by epatrick** [comment]
Do you have an ETA on moving to async methods?

**Comment by garg-mudit** [comment]
Hi @bbarry , @epatrick ,
Async variants of above mentioned methods were added with out most recent [release](https://www.nuget.org/packages/DocuSign.eSign.dll/8.0.1). 
Marking this issue as completed. Feel free to reopen the same or create a new one in case you find any issue with the same.

Thank You.
