### ISSUE TITLE
Docusign Setting "iat" parameter in C#

### ISSUE THREAD

**Issue by sameedaris** [docusign/docusign-esign-csharp-client#324]
Hello, 
Currently DocuSign client is setting current system time as "iat" parameter. This causes issue when system time is not correct. As this is not required parameter from DocuSign we would like to know how to set it to null ?
Thanks.

**Comment by ivdinkovds** [comment]
@sameedaris According to the [code](https://github.com/docusign/docusign-csharp-client/blob/613fcc11048b65e25cd974908255edd7df92b491/sdk/src/DocuSign.eSign/Client/ApiClient.cs#L995) 
`IssuedAt = DateTime.UtcNow,`
According to Microsoft UtcNow
`Gets a DateTime object that is set to the current date and time on this computer, expressed as the Coordinated Universal Time (UTC).`
I would advise making sure your server time is correctly synced 
You can not set it to NULL, this value will be assigned at run time based on your server time

**Comment by sameedaris** [comment]
This is reply from docusign support:

_After reviewing with my internal team, this error appears to be caused by an incorrect server time.  In order to resolve, your client will need to ensure their server clock is correct & synced.  Otherwise, should the time be correct, it may help to manually build in some slack such as "current time - 5 minutes" or not setting the 'iat' parameter as it is not required, unlike the 'exp' parameter which is required._

**Comment by ivdinkovds** [comment]
@sameedaris [RequestJWTUserToken](https://github.com/docusign/docusign-csharp-client/blob/613fcc11048b65e25cd974908255edd7df92b491/sdk/src/DocuSign.eSign/Client/ApiClient.cs#L995) method requires only expiration time. **"iat"** is set in the method itself  **IssuedAt = DateTime.UtcNow** at run time and is using server time. You can not set it to NULL or alter it. I am really not sure what **manually build in some slack such as "current time - 5 minutes"** means.

**Comment by ivdinkovds** [comment]
I assume you can manually build your assertion and directly call the auth endpoint but because you have opened an issue here I guess you plan to use the SDK client

**Comment by sameedaris** [comment]
Thanks  All the help @ivdinkovds .

**Comment by avinfinity** [comment]
Closing this issue as it has been already resolved. Thanks
