### ISSUE TITLE
ApiClient OAuthBasePath stubbing

### ISSUE THREAD

**Issue by raman-nareika** [docusign/docusign-esign-csharp-client#337]
Hi.
We were successfully using [DocuSign.NetCore](https://www.nuget.org/packages/DocuSign.NetCore/) in pair with WireMock for tests. But after upgrade to DocuSign.eSign V5.5.0 I can't mock ApiClient.RequestJWTUserToken because of a non-successful HTTP code.

Flow is the following:
1. launch WireMock on 127.0.0.1:19257
2. set `BasePath` to `http://127.0.0.1:19257/docusignapi`
3. Mock a call. For example, for `$"/docusignapi/v2.1/accounts/{accountId}/envelopes/{response.EnvelopeId}/recipients"))` I return needed json

But for authorization `OAuthBasePath` is used instead of  `BasePath`. When I try to set `OAuthBasePath` to ``http://127.0.0.1:19257/auth` and mock requests I get the error while requesting the server.

Is it possible to stub and get an access token with JWT Grant authentication locally instead of calling `account-d.docusign.com/oauth/token`?

Thank you in advance.

**Comment by LarryKlugerDS** [comment]
I've submitted support case 08072430 on your behalf.

**Comment by GlorianaMarinDS** [comment]
Hello Raman,

My name is Gloriana and I am part of DocuSign's developer support team. 

If you downgrade back to your previous version, are you able to make this successfully? If so, what version is able to complete this correctly? Can you also please provide a code sample on how you are generating your JWT token? 

Also, regarding your question the only existing base URL to obtain JWT tokens is account-d.docusign.com/oauth/token.

**Comment by raman-nareika** [comment]
Hello Gloriana.
[My previous version](https://github.com/mitchdowd/DocuSign.NetCore) is a legacy one. It's a fork of the official API. So, yes, authorization is mocked successfully but this version supports only DocuSign legacy authentication and JWT Grant authentication doesn't. We upgrade SDK because the legacy `X-DocuSign-Authentication` header will not be supported.

Sample:

`var apiClient = new ApiClient(configuration.BaseUrl);`
`var privateKey = File.ReadAllBytes(configuration.PrivateKeyPath);`
`var accessToken = apiClient.RequestJWTUserToken(`
                   `configuration.IntegrationKey,`
                    `configuration.UserId,`
                    `configuration.OAuthBasePath,`
                    `privateKey,`
                    `configuration.ExpiresInHours,`
                    `configuration.Scopes);`

`BaseUrl` is `http://127.0.0.1:19257/docusignapi`
`OAuthBasePath` is `http://127.0.0.1:19257/auth`

Content of the test key file is:
`-----BEGIN RSA PRIVATE KEY-----
<Enter RSA private key here>
-----END RSA PRIVATE KEY-----`

The prod key file content is real and contains the key that was generated on the `Apps and Keys` page.

I believe the key file content doesn't cause the exception. It appears because of incorrect `OAuthBasePath`

**Comment by GlorianaMarinDS** [comment]
Hello Raman,

My recommendation would be to make sure your application is requesting the token by hitting account-d.docusign.com/oauth/token. This is currently the only available base path for all authentication methods.
