### ISSUE TITLE
Multiple Account session with Esign Dll

### ISSUE THREAD

**Issue by sameedaris** [docusign/docusign-esign-csharp-client#343]
Hello,
Guys I want to give ability for using multiple docusign accounts inside my application . but when I am trying to run multiple sessions it is giving me error like "User is not related to account" "Invalid integration key"  during single account session everything works fine. 
Kindly guide if multiple docusign sign accounts can be used with this Dll? or there are some static variables that will always cause issues?

**Comment by RajRele** [comment]
Can you elaborate on how you are using multiple accounts inside you app? 
Are the accounts you are using list in the userInfo Accounts response? see this https://github.com/docusign/docusign-esign-csharp-client/blob/master/test/SdkNetCoreTests/JwtAuthNetCoreUnitTests.cs#L39

**Comment by garg-mudit** [comment]
Closing this issue due to no further response from customer.
Please feel free to reopen this issue or create a new one in case you feel the need.

Thank You.
