### ISSUE TITLE
Listing all users but need more than one API call

### ISSUE THREAD

**Issue by NJarZe** [docusign/docusign-esign-csharp-client#348]
Using the UsersApi.List method to retrieve the list of all users in a DocuSign account; however, one of our accounts has more than 100 users, which is the maximum I can get in one call (using the count option) as per the documentation.

How do you manage the subsequent calls from the UsersApi class (using the nexturi value)?

**Comment by HobbyProjects** [comment]
Please refer to this blog:https://www.docusign.com/blog/developers/v2-userslist-paging-change

It should give you a pretty good idea of how this API works. If you're still unclear please reach out to our StackOverFlow and post a question there and someone will be happy to provide you with a code example.

https://stackoverflow.com/search?q=docusignapi
