### ISSUE TITLE
Newtonsoft.Json versioning issue while attempting to authenticate with JWT using DocuSign.eSign

### ISSUE THREAD

**Issue by ha-cmhheli** [docusign/docusign-esign-csharp-client#364]
Not sure what I'm doing wrong if anything but I can't get basic JWT authentication working with the latest package
Scenario:
.NET 4.7.2 c# Test project 
Using DocuSign.eSign.dll v5.9.0
No other nuget packages added
Very simple test method.   
This line: ApiClient apiClient = new ApiClient(@"https://www.docusign.net/restapi");  appears to need Newtonsoft.Json v11.0.2
This line:  OAuthToken authToken = apiClient.RequestJWTUserToken(clientId, userId, oathPath, Encoding.UTF8.GetBytes(rsaKey), expiresIn1Hour, scopes);  appears to need Newtonsoft.Json v10.0.0.0

   [TestMethod]

        public void TestAuth()
        {
            string clientId = ""; // removed for issue
            string userId = ""; // removed for issue
            string oathPath = @"https://account.docusign.com/oauth/auth";

            ApiClient apiClient = new ApiClient(@"https://www.docusign.net/restapi");

            int expiresIn1Hour = 1;
            string rsaPath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "RSAPrivateKey.txt");
            string rsaKey = System.IO.File.ReadAllText(rsaPath);
            var scopes = new List<string> { "signature" };

            OAuthToken authToken = apiClient.RequestJWTUserToken(clientId, userId, oathPath, Encoding.UTF8.GetBytes(rsaKey), expiresIn1Hour, scopes);

            Assert.IsNotNull(authToken);
        }

Error:
System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'System.IdentityModel.Tokens.Jwt.JsonExtensions' threw an exception.
  Source=System.IdentityModel.Tokens.Jwt
  StackTrace:
   at System.IdentityModel.Tokens.Jwt.JsonExtensions.SerializeToJson(Object value)
   at System.IdentityModel.Tokens.Jwt.JwtHeader.SerializeToJson()
   at System.IdentityModel.Tokens.Jwt.JwtHeader.Base64UrlEncode()
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.CreateJwtSecurityTokenPrivate(String issuer, String audience, ClaimsIdentity subject, Nullable`1 notBefore, Nullable`1 expires, Nullable`1 issuedAt, SigningCredentials signingCredentials, EncryptingCredentials encryptingCredentials)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.CreateToken(SecurityTokenDescriptor tokenDescriptor)
   at DocuSign.eSign.Client.ApiClient.RequestJWTUserToken(String clientId, String userId, String oauthBasePath, Byte[] privateKeyBytes, Int32 expiresInHours, List`1 scopes)
   at CMHInc.DocuSign.Test.DocuSignClientTest.TestBasic() in C:\Users\harmitage\source\repos\Reservations\CMHInc.DocuSign.Test\DocuSignClientTest.cs:line 85

  This exception was originally thrown at this call stack:

Inner Exception 1:
FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

**Comment by aardvark79** [comment]
I am having the same issue, except I'm on .NET 5, and with the same DocuSign.eSign.dll version as you (5.9.0), mine is complaining that it can't find Newtonsoft.Json, Version=11.0.0.0.

**Comment by kenharris** [comment]
I'm Ken, a Software Developer at Docusign.

I wanted to reach out to see if you're still experiencing this issue. I haven't been able to reproduce it in a .NET 4.7.2 test project using the 5.9.0 version of the eSign NuGet package. Using the code snipped that you provided, my test method compiles and completes successfully in Visual Studio 2022.  The only NuGet package added to my test project was the eSign NuGet package and my test project has only the one test method.

Which version of Visual Studio are you using?  Also, are there any other dependencies in your test project?

**Comment by ha-cmhheli** [comment]
Hi,
This issue has been resolved with binding redirects in the config file.
Thanks,
Heather

**Comment by avinfinity** [comment]
As confirmed in previous thread, this issue is not more happening. Hence closing this issue. Thanks
