### ISSUE TITLE
Hi, Any help in making it work with dot NET Core 6.0 ? Throwing Platform Not Supported error when i  try similiar code.

### ISSUE THREAD

**Issue by dolphin-digital** [docusign/docusign-esign-csharp-client#369]

**Comment by RajRele** [comment]
@dolphin-digital , could you share and add more details on your project, what DocuSign sdk version you are trying to install and what targetframework and so on.

**Comment by garg-mudit** [comment]
Closing this issue due to no further response from customer.
Please feel free to reopen this issue or create a new one in case you feel the need.

Thank You.
