### ISSUE TITLE
How to update envelope status from created to sent?

### ISSUE THREAD

**Issue by harshac2b2** [docusign/docusign-esign-csharp-client#382]
May I know how to set the envelopeStatus of an envelope that's in draft status("created") to "sent"? This way I can now send the envelope to all the recipients?

1) I created the envelope by creating EnvelopeDefinition and assigning the documents and other metadata followed by setting the EnvelopeDefinition Status to "created". This has definitely put the envelope in draft status instead of sending it to the end user and this is exactly what I wanted.

  **envDef.Status = "created";
  var envelopesApi = new EnvelopesApi(apiClient);
  EnvelopeSummary envelopeSummary = envelopesApi.CreateEnvelope(accountID, envDef);**

2) Now, after another process brings in additional documents and recipients info I now have updated to include them in the envelope above(using the same envelopeID generated in step#1) by setting the EnvelopeDefinition Status to "sent". This time I don't see any difference and the envelope is still sitting in the Draft status while the envelope got updated with the additional documents.

**envDef1.Status = "sent";
EnvelopeDocumentsResult res = envelopesApi.UpdateDocuments(accountID, envelopeSummary.EnvelopeId, envDef1)**

May I know if I'm missing anything here? (or) Call additional DocuSign endpoint to now move the envelope to "sent" status so that it will be sent to the recipients?

Thanks in advance.

**Comment by HunterWDocu** [comment]
Hello @harshac2b2,

If the Update call is returning successful, and the only data not properly getting updated is the envelope's status, then I believe it's safe to assume that your system is not properly setting the envelope's status = "sent". Are you able to provide a small code example of this call request?

If you feel more comfortable you can open a support case to our Developer Support channel and a support engineer will be able to assist you with this issue. https://developers.docusign.com/support/

**Comment by InbarGazit** [comment]
need to call Update() not UpdateDocuments()
