### ISSUE TITLE
Starting a new project on .NET 6

### ISSUE THREAD

**Issue by pvanroos** [docusign/docusign-esign-csharp-client#385]
Hi,

I'm starting a new project on .NET 6 and would like to use the newest version 6.0.0 of the DocuSign.eSign.dll, however it's still in prerelease as an RC.

Any guidance here?  Should I go with the RC with a full GA release expected soon?

**Comment by RajRele** [comment]
Hi @pvanroos , we would suggest as you are just starting out with your project you can start testing with the latest rc release, we have made nice improvements over it and we are hoping there won't be any breaking changes when we go full GA.

Happy Coding!
Bharat

**Comment by pvanroos** [comment]
Not trying to pressure you but is GA expected in the next 2 months?

**Comment by jglassenberg** [comment]
Sorry for the late reply here.  This went GA in September.

**Comment by kenharris** [comment]
This appears to be resolved; closing the issue.
