### ISSUE TITLE
ENVELOPE_CUSTOM_FIELD_MISSING after Client Update

### ISSUE THREAD

**Issue by insanity13** [docusign/docusign-esign-csharp-client#386]
We have template with Custom field with empty "Required for Sending" option.
![image](https://user-images.githubusercontent.com/1174911/187387815-2c88a077-f8ec-436a-abe6-a2174f57e5a9.png)

In DocuSign.eSign.dll" version="3.0.1" it worked well

After update to 5.12.0 we got:
`'Error calling CreateEnvelope: {"errorCode":"ENVELOPE_CUSTOM_FIELD_MISSING","message":"A required envelope custom field is missing. The custom field 'Vault With eOriginal' requires a value."}'`

If this field set to "False" it worked
![image](https://user-images.githubusercontent.com/1174911/187388287-d8236830-1dfe-482f-89b7-9830a38455e3.png)

We have a lot of such templates, is it a way to change default behaviour?

p.s. yes it is required in global settings
![image](https://user-images.githubusercontent.com/1174911/187389114-f98e76f6-9eb3-4f6d-8562-ae01294f0d96.png)

**Comment by sylvainleb376** [comment]
In fact if this envelope custom field has the property Required=true, then it's mandatory to have a value attributed to this field when an envelope is sent.
A solution is to pre-define a value directly in the template as you did. Or to attribute a value during the envelope creation. See an example in this blog: https://www.docusign.com/blog/developers/the-trenches-track-your-templates-envelope-custom-fields

**Comment by insanity13** [comment]
Thanks
