### ISSUE TITLE
ASP.NET 6.0 Downloading completed document is not working on newest package 6.0.0

### ISSUE THREAD

**Issue by gagyn** [docusign/docusign-esign-csharp-client#389]
I'm downloading file using method:
```
var stream = await envelopesApi.GetDocumentAsync("<api account ID>", envelopeId, envelopeDocumentId);
```
Then I'm saving the stream on my disk.
```
using var fileStream = new FileStream("signed_pdf.pdf", FileMode.Create, FileAccess.Write);
stream.CopyTo(fileStream);
Console.ReadKey();
```
**But when I try to open this freshly saved file, I'm getting an error** (tried to open it with Edge browser and Acrobat Reader - both we same result). **The PDF file is probably broken**.

The code on my side is correct I believe, because when I install the **older version** of DocuSign nuget package (5.12.0) **everything is fine**.

Here are two files, one saved using newest package, and second saved using 5.12.0 (take a look on the difference in size - both comes from the same envelope and same document):
![image](https://user-images.githubusercontent.com/35143425/195108199-81e57a30-06f5-4aa1-8777-33579bb01365.png)

I tried to spot the bug in code, but didn't have time to debug it, so I just guess that it can be somewhere here in DocuSignClient class:

![image](https://user-images.githubusercontent.com/35143425/195109991-0942b318-3696-4fc4-b5b6-babca4453d99.png)

As previous version was just returning MemoryStream:

![image](https://user-images.githubusercontent.com/35143425/195110137-d795df79-3446-4a23-bdf9-2d3684a1f0db.png)

**Comment by bbarry** [comment]
That code: https://github.com/docusign/docusign-esign-csharp-client/blob/e23718c14dd7482de90bfe55e9cbd245f182868e/sdk/src/DocuSign.eSign/Client/DocuSignClient.cs#L326

is very wrong... 

It is potentially writing unencrypted PII to a temp path. Whether or not it is the cause of this issue it should be reverted asap as a security vulnerability. 

In the event that this library is being used in an environment where something else has access to the file system, unrelated parties could gain access to sensitive information related to an authorized individual.

**Comment by kenharris** [comment]
Thanks for these reports.  Our team will be engaged in evaluating the issues mentioned here.

**Comment by gagyn** [comment]
Thanks! It would be nice to have it sorted soon 🙂
Can you also please look into my PR? :)

**Comment by kenharris** [comment]
Hi, yes our team will also take a look at your PR; thanks for your contribution.

**Comment by skyflyer** [comment]
Hello guys!

Any updates on the release date of the updated library?

**Comment by kenharris** [comment]
Hi @skyflyer - [v6.1.0](https://www.nuget.org/packages/DocuSign.eSign.dll/6.1.0) was released today and should contain a fix for the issue.

**Comment by skyflyer** [comment]
@kenharris thanks for the update!
