### ISSUE TITLE
EnvelopesApi sync methods dead lock net48 WebForms. Issue since 6.1 version.

### ISSUE THREAD

**Issue by dandros** [docusign/docusign-esign-csharp-client#399]
EnvelopesApi sync methods dead lock net48 WebForms. Issue since 6.1 version.

It looks like GetAwaiter doesn't work well in WebForms.

I confirm that latest console code example works perfectly. However when in WebForms, then EnvelopesApi sync methods are dead on arrival. 

I didn't test WebForms Async tricks with EnvelopesApi async methods.

**Comment by DSDemo-LeandroReis** [comment]
Hello there,

Before we dive in, I need some clarification. Please answer the questions below:

1. Does this work in previous versions (e.g.: 6.0)?
2. What is the error message you're getting? Do you have a log?
3. What exactly do you mean by _"However when in WebForms, then EnvelopesApi sync methods are dead on arrival"_?

Thanks,
Leandro

**Comment by dandros** [comment]
Please find below answers:
1. Yes it works fine in previous version 6.0
2. There is no error message. Or I didn't wait long enough to see the error.. The underlying call to DocuSign API works. Envelope is created. However the method call to EnvelopesApi.CreateEnvelope just never returns.
3. I mean version 6.2 works fine in net48 Console application. However it doesn't work in net48 ASP.NET Web Forms application. Method call to EnvelopesApi.CreateEnvelope never returns.

I guess the following GetAwaiter() doesn't work in ASP.NET Web Forms. 

` return CreateEnvelopeAsyncWithHttpInfo(accountId, envelopeDefinition, options)
.ConfigureAwait(false)
.GetAwaiter()
.GetResult();`

Special considerations should be taken to use Asynchronous methods in ASP.NET Web Forms.
https://learn.microsoft.com/en-us/aspnet/web-forms/overview/performance-and-caching/using-asynchronous-methods-in-aspnet-45

Best regards,
Dimitri

**Comment by kenharris** [comment]
Hello there, could you provide a small code sample that replicates your issue?

**Comment by dandros** [comment]
[WebApplication1.zip](https://github.com/docusign/docusign-esign-csharp-client/files/10931530/WebApplication1.zip)

Set your ClientId and ImpersonatedUserID in web.config
Put private key file and lorem.pdf in C:\Temp\_files

**Comment by kenharris** [comment]
Just wanted to provide a quick update on this issue - the team was able to re-produce the issue and is currently looking into a fix.

**Comment by Welchen** [comment]
We just ran into the same issue with .NET 4.8 WebForms synchronous methods and any version of the client over 6.0.

**Comment by Welchen** [comment]
> Just wanted to provide a quick update on this issue - the team was able to re-produce the issue and is currently looking into a fix.

@kenharris any eta on a fix?

**Comment by kenharris** [comment]
A new update was just released moments ago - v6.4.1 - which should have a fix to address this issue.

**Comment by kenharris** [comment]
I'm going to close this for now. Feel free to re-open if the issue persists, or just open a new issue.
