### ISSUE TITLE
EnvelopesApi.GetDocument() contains broken words for signer name

### ISSUE THREAD

**Issue by kongshu612** [docusign/docusign-esign-csharp-client#401]
Hi there,

when I call ` envelopesApi.GetDocument(AccountId, envelopeId, "combined",
 new EnvelopesApi.GetDocumentOptions { certificate = "false",})`, I found the downloaded files contains borken word for signer name.  But if I don't pass the **GetDocumentOptions** parameter, it works fine. 

It should be some private parameters released to the Docusign Server side. it only happens in Production environment. Seems the default value for the private parameters is not fine.  If possible, Could you help to forward to some one to check this?

**Comment by sylvainleb376** [comment]
I think it would be better you open directly a case on the Docusign Support Center.
You could then share API logs, identifiers and downloaded files that could help us to troubleshoot this issue.
Thanks

**Comment by garg-mudit** [comment]
Hi @kongshu612 ,
Wanted to check if you were able to resolve the issue ?

Thank you.

**Comment by garg-mudit** [comment]
Closing this issue due to no further response from customer.
Please feel free to reopen this issue or create a new one in case you feel the need.

Thank You.
