### ISSUE TITLE
BouncyCastle

### ISSUE THREAD

**Issue by joshjeppson** [docusign/docusign-esign-csharp-client#403]
Since [BouncyCastle 1.8.9](https://www.nuget.org/packages/BouncyCastle/1.8.9) has been deprecated, are there plans to migrate to [BouncyCastle.Cryptography 2.1.1](https://www.nuget.org/packages/BouncyCastle.Cryptography)? If so, ETA? If not, why?

**Comment by karankaushik95** [comment]
There is currently a task to have this updated. Internal tracking id for this is DCM-8877

If you wish to add in your details to this, you can open a support case with DocuSign Developer Support referencing this ID and your support representative can add on your details to this. Currently no ETA available to share.
