### ISSUE TITLE
Adding document to existing template

### ISSUE THREAD

**Issue by ymazlumyan** [docusign/docusign-esign-csharp-client#405]
Hello,
I am trying to add/attach a document to an existing template. I am new to DocuSign, so this might seem like a silly question. I am able to get a document, create template and recipients, but can't find a way actually add a document to the template. I have tried adding to the template object and then running the Update method using the .NET SDK, but that doesn't seem to do the trick.

**Comment by ivan-dinkov** [comment]
@ymazlumyan This place is for the C# Client issues. If you need help on how to do something you may try StackOverflow or perhaps open a case through the [Support Center](https://support.docusign.com/s/?language=en_US&rsc_301). It looks like the same question was already answered https://stackoverflow.com/questions/59710240/docusign-api-update-template-pdf-document

**Comment by garg-mudit** [comment]
Hi @ymazlumyan ,
Wanted to check if you were able to fix your issue with the help of links provided by @ivan-dinkov .

Thank You.

**Comment by garg-mudit** [comment]
Closing this issue due to no further response from customer.
Please feel free to reopen this issue or create a new one in case you feel the need.

Thank You.
