### ISSUE TITLE
Vulnerable System.Text.RegularExpressions

### ISSUE THREAD

**Issue by romanb52** [docusign/docusign-esign-csharp-client#411]
Hello,
docusign.esign references vulnerable System.Text.RegularExpressions. 4.3.0

See: https://github.com/advisories/GHSA-cmhx-cq75-c4mj

**Comment by karankaushik95** [comment]
Thanks for raising this. I'll raise this to our SDK team to act on it as needed.

**Comment by garg-mudit** [comment]
Hi @romanb52 ,
Can you please let me know if this vulnerability still exists with eSign code ?
I am unable to find this dependency. Is this a transitive dependency ?

Thank You.
