### ISSUE TITLE
Getting 500 error code for SDK on API calls with no ErrorMessage details.

### ISSUE THREAD

**Issue by jaypman** [docusign/docusign-esign-csharp-client#417]
I passed in a valid accessToken which I got from the Authorization Code Grant Flow.  Called API.   Getting this error with no detailed information on what the issue is.   Am I missing something?  I also checked the API Request Log section in the Account dashboard.. nothing..

var docuSignClient = new DocuSignClient("https://demo.docusign.net/restapi");
docuSignClient.Configuration.DefaultHeader.Add("Authorization", $"Bearer {accessToken}");
var envelopesApi = new EnvelopesApi(docuSignClient);

 // Prepare the envelope definition
            var envelopeDefinition = new EnvelopeDefinition
            {
                EmailSubject = "Please sign this document",
                Documents = new List<Document>
                {
                    new Document
                    {
                        DocumentBase64 = documentBase64,
                        Name = "TestDocument.pdf",
                        FileExtension = "pdf",
                        DocumentId = "1"
                    }
                },
                Recipients = new Recipients
                {
                    Signers = new List<Signer>
                    {
                        new Signer
                        {
                            Email = signerEmail,
                            Name = signerName,
                            RecipientId = "1",
                            Tabs = new Tabs
                            {
                                SignHereTabs = new List<SignHere>
                                {
                                    new SignHere
                                    {
                                        DocumentId = "1",
                                        PageNumber = "1",
                                        RecipientId = "1",
                                        TabLabel = "SignHereTab",
                                        XPosition = "100",
                                        YPosition = "100"
                                    }
                                }
                            }
                        }
                    }
                },
                Status = "sent"
            };

  try
  {
                // Call the create envelope endpoint using the SDK method
                var results = await envelopesApi.CreateEnvelopeAsync(AccountId, envelopeDefinition);
                return results.EnvelopeId;
  }

 catch (ApiException ex)
 {
       var errorCode = ex.ErrorCode;  // **returns 500**
       var errorMessage = ex.ErrorMessage;  // **returns ""**

 }

**ex.Message returns this**: 

Error calling CreateEnvelope: <!DOCTYPE html>
<html>
    <head>
        <title>Runtime Error</title>
        <meta name="viewport" content="width=device-width" />
        <style>
         body {font-family:"Verdana";font-weight:normal;font-size: .7em;color:black;} 
         p {font-family:"Verdana";font-weight:normal;color:black;margin-top: -5px}
         b {font-family:"Verdana";font-weight:bold;color:black;margin-top: -5px}
         H1 { font-family:"Verdana";font-weight:normal;font-size:18pt;color:red }
         H2 { font-family:"Verdana";font-weight:normal;font-size:14pt;color:maroon }
         pre {font-family:"Consolas","Lucida Console",Monospace;font-size:11pt;margin:0;padding:0.5em;line-height:14pt}
         .marker {font-weight: bold; color: black;text-decoration: none;}
         .version {color: gray;}
         .error {margin-bottom: 10px;}
         .expandable { text-decoration:underline; font-weight:bold; color:navy; cursor:pointer; }
         @media screen and (max-width: 639px) {
          pre { width: 440px; overflow: auto; white-space: pre-wrap; word-wrap: break-word; }
         }
         @media screen and (max-width: 479px) {
          pre { width: 280px; }
         }
        </style>
    </head>

    <body bgcolor="white">

            <span><H1>Server Error in '/' Application.<hr width=100% size=1 color=silver></H1>

            <h2> <i>Runtime Error</i> </h2></span>

            <font face="Arial, Helvetica, Geneva, SunSans-Regular, sans-serif ">

            <b> Description: </b>An exception occurred while processing your request. Additionally, another exception occurred while executing the custom error page for the first exception. The request has been terminated.
            <br><br>

            </font>

    </body>
</html>

**Comment by troywdocusign** [comment]
Hi,

If there are no logs in the API Logs dashboard then I doubt your code is working & reaching the DocuSign API. You could look at ex.InnerException to try to find the detail.

Otherwise I suggest you checkout https://apirequestbuilder.docusign.com/ which connects directly to your developer account & generates code, I have done this and it works perfectly with my generated code.

Here is your code snippet which worked for me on my developer account with some minor changes

`
using System.Collections.Generic;
using System.IO;
using System;
using DocuSign.eSign.Api;
using DocuSign.eSign.Client;
using DocuSign.eSign.Model;

namespace CSharp_example
{
    class Program
    {
        private const string accessToken = "XXXX";
        private const string accountId = "XXXX";

        private const string AccountId = accountId;
        private const string documentBase64 = "XXXX";
        private static string signerEmail = "test@test.com";
        private static string signerName = "Test Signer";

        static async Task<string> SendEnvelope()
        {
            var docuSignClient = new DocuSignClient("https://demo.docusign.net/restapi");
            docuSignClient.Configuration.DefaultHeader.Add("Authorization", $"Bearer {accessToken}");
            var envelopesApi = new EnvelopesApi(docuSignClient);

            // Prepare the envelope definition
            var envelopeDefinition = new EnvelopeDefinition
            {
                EmailSubject = "Please sign this document",
                Documents = new List<Document> 
                { 
                    new Document
                    {
                        DocumentBase64 = documentBase64,
                        Name = "TestDocument.pdf",
                        FileExtension = "pdf",
                        DocumentId = "1"
                    }
                },
                Recipients = new Recipients
                {
                    Signers = new List<Signer>
                    {
                        new Signer
                        {
                            Email = signerEmail,
                            Name = signerName,
                            RecipientId = "1",
                            Tabs = new Tabs
                            {
                                SignHereTabs = new List<SignHere>
                                {
                                    new SignHere
                                    {
                                        DocumentId = "1",
                                        PageNumber = "1",
                                        RecipientId = "1",
                                        TabLabel = "SignHereTab",
                                        XPosition = "100",
                                        YPosition = "100"
                                    }
                                }
                            }
                        }
                    }
                },
                Status = "sent"
            };

            try
            {
                // Call the create envelope endpoint using the SDK method
                var results = await envelopesApi.CreateEnvelopeAsync(AccountId, envelopeDefinition);
                return results.EnvelopeId;
            }

            catch (ApiException ex)
            {
                var errorCode = ex.ErrorCode; // returns 500
                var errorMessage = ex.ErrorMessage; // returns ""
            }

            return "";
        }

        // The mainline
        static void Main()
        {
            MainAsync().GetAwaiter().GetResult();
        }
        static async Task MainAsync()
        {
            Console.WriteLine("Starting...");
            string envelopeId = await SendEnvelope();
            Console.WriteLine("Done - EnevelopeId: " + envelopeId);
        }
    }
}
`

**Comment by troywdocusign** [comment]
No problem at all, glad to help.

You should be using the DocuSignClient has the ApiClient has been marked as [Obsolete](https://github.com/docusign/docusign-esign-csharp-client/blob/master/sdk/src/DocuSign.eSign/Client/ApiClient.cs)

**Comment by garg-mudit** [comment]
Hi @jaypman ,
Were you able to get it working via DocuSignClient ?

**Comment by garg-mudit** [comment]
Closing this issue due to no further response from Customer.
Please feel free to reopen this issue or create a new one in case you feel the need.

Thank You.
