### ISSUE TITLE
UpdateRecipientsOptions resendEnvelope not working

### ISSUE THREAD

**Issue by Bgosse1** [docusign/docusign-esign-csharp-client#418]
Is there an issue with the resendEnvelope property in the UpdateRecipientsOptions object.

I am calling the envelope API UpdateRecipients method with UpdateRecipientsOptions { resendEnvelope = "true" }.

Recipients that have correct emails are getting the resent envelope notifications.

Updating recipients with a status of auto responded to use a correct email are not being resent.

Seems to be only happening with the API call, seems to be working fine when I click resend in the DocuSign portal.

FYI, using a developer account. Version 5.9.0 NuGet package

**Comment by InbarGazit** [comment]
Try this code instead:
```
options.resendEnvelope = "true";
Envelope envelope = new Envelope();
envelope.EnvelopeId = envelopeId;
envelopesApi.Update(accountId, envelopeId, envelope, options);

```

**Comment by Bgosse1** [comment]
@InbarGazit Is it better practice to update the entire envelope and not just the list of recipients?

**Comment by Bgosse1** [comment]
@InbarGazit If I call UpdateRecipients twice then the resend goes through.  It's behaving like the resend is happening before the updating of recipients happens, so the resend is still being sent to the old recipient data.

**Comment by Bgosse1** [comment]
@InbarGazit 

> Try this code instead:
> 
> ```
> options.resendEnvelope = "true";
> Envelope envelope = new Envelope();
> envelope.EnvelopeId = envelopeId;
> envelopesApi.Update(accountId, envelopeId, envelope, options);
> ```

I'm seeing the same result with the code you suggested. 

When I initially send an envelope with a recipient that has an invalid email and Update the envelope recipients to contain a correct email the DocuSign portal show the updated recipient info but the Auto Responded error message is still showing.

**Comment by shan285** [comment]
Hi @Bgosse1, Could you please let us know if you are still facing the issue with the mentioned scenario? We would be happy to help you out.

**Comment by garg-mudit** [comment]
Closing this issue due to no further response from customer.
Please feel free to reopen this issue or create a new one in case you feel the need.

Thank You.
