### ISSUE TITLE
Upgrade ancient IdentityModel dependencies

### ISSUE THREAD

**Issue by Mertsch** [docusign/docusign-esign-csharp-client#423]
The NuGet package https://www.nuget.org/packages/DocuSign.eSign.dll#dependencies-body-tab depends on
```
Microsoft.IdentityModel.Protocols (>= 5.4.0)
System.IdentityModel.Tokens.Jwt (>= 5.4.0)
```

both are really old and contain a lot of redundant dependencies of the pre-`netstandard2.0` area like
```
NETStandard.Library (>= 1.6.1)
System.Collections.Specialized (>= 4.3.0)
System.Diagnostics.Contracts (>= 4.3.0)
System.Net.Http (>= 4.3.0)
```

Please update them to their 7.x version which contain all required support for modern .NET and legacy .NET Framework, just like DocuSign.

**Comment by kollDocuSign** [comment]
Hi @Mertsch. I'm with the developer support team at DocuSign. When issues like this are created it automatically creates a DocuSign developer support case. 
I have created an internal enhancement request for this Jira issue you've raised. The request number is DCM-10148. 
I can't give an ETA on if or when it will be addressed but it is now logged with our engineering team.

**Comment by garg-mudit** [comment]
Hi @Mertsch,
The changes have been implemented with the latest RC release, version [7.0.0-rc2](https://github.com/docusign/docusign-esign-csharp-client/releases/tag/v7.0.0-rc2).  We anticipate a stable release by the end of this month.

Please do test the changes and let us know if you encounter any issues. I'll keep this issue open until we release the stable version.
Thank You.

**Comment by Mertsch** [comment]
Works for me.

A general idea for another improvement would be to support .NET 8 (and 6) directly, which would help to reduce the references even more. You might consider that as .NET Standard is dying.

**Comment by garg-mudit** [comment]
Hi @Mertsch,
Thanks for your suggestion!

We appreciate your input regarding supporting .NET 8 (and 6) directly. It's definitely something we'll look into further. Our team will review the suggestion and see how we can integrate it into our plans moving forward.

Thanks again for sharing your thoughts!
