### ISSUE TITLE
Method Missing AccountsApi.UpdateReportInProductRunResultsAsync(string, ReportInProductRunRequest)

### ISSUE THREAD

**Issue by brian-swart** [docusign/docusign-esign-csharp-client#429]
This method was available in the 5.10.0 version of the C# SDK but has since been removed. There are no deprecation notices in that version of the API and I can't find a comparable method in later versions of the API. What is the replacement method for this method call?

I have a customized report that I set up to download data that I used this method call for.

Thanks!

Brian

**Comment by avinfinity** [comment]
Closing this ticket, as mentioned method is no more supported/intended for public usage anymore. Thanks
