### ISSUE TITLE
EnvelopesApi sync methods dead lock net48 WebForms is back in version 8.0.0

### ISSUE THREAD

**Issue by dandros** [docusign/docusign-esign-csharp-client#454]
This is the same problem that was solved in issue #399 It's back now.

EnvelopesApi sync methods dead lock net48 WebForms

**Comment by dandros** [comment]
Since it is a recurrent issue, I guess I will try update my ASP.NET WebForms code to use Asynchronous Methods
https://learn.microsoft.com/en-us/aspnet/web-forms/overview/performance-and-caching/using-asynchronous-methods-in-aspnet-45

**Comment by dandros** [comment]
So I updated my WebForms code to use only Async api methods, including RequestJWTUserTokenAsync which is an improvement in 8.0.0. 
All works fine now.

**Comment by garg-mudit** [comment]
Hi @dandros ,
This should be resolved with the recent [Patch release](https://www.nuget.org/packages/DocuSign.eSign.dll/8.0.1).

I'll be closing the issue as completed, but please to reopen the same in case the issue persists for you.

Thank You.
